// Lista inicial do campo "Modelo do veículo" nos modelos de O.S. (spec 0075).
// É só o ponto de partida: a empresa edita a lista nas propriedades do campo.

export const STARTER_VEHICLE_MODELS: string[] = [
  "BYD Dolphin", "BYD Dolphin Mini", "BYD King", "BYD Song Plus", "BYD Yuan Plus",
  "Caoa Chery Arrizo 6", "Caoa Chery Tiggo 5X", "Caoa Chery Tiggo 7", "Caoa Chery Tiggo 8",
  "Chevrolet Celta", "Chevrolet Classic", "Chevrolet Cobalt", "Chevrolet Cruze", "Chevrolet Equinox",
  "Chevrolet Montana", "Chevrolet Onix", "Chevrolet Onix Plus", "Chevrolet Prisma", "Chevrolet S10",
  "Chevrolet Spin", "Chevrolet Tracker", "Chevrolet Trailblazer",
  "Citroën Basalt", "Citroën C3", "Citroën C3 Aircross", "Citroën C4 Cactus",
  "Fiat 500", "Fiat Argo", "Fiat Cronos", "Fiat Doblò", "Fiat Fastback", "Fiat Fiorino", "Fiat Mobi",
  "Fiat Palio", "Fiat Pulse", "Fiat Siena", "Fiat Strada", "Fiat Titano", "Fiat Toro", "Fiat Uno",
  "Ford Bronco Sport", "Ford EcoSport", "Ford Fiesta", "Ford Focus", "Ford Ka", "Ford Maverick",
  "Ford Ranger", "Ford Territory",
  "GWM Haval H6", "GWM Ora 03",
  "Honda City", "Honda Civic", "Honda CR-V", "Honda Fit", "Honda HR-V", "Honda WR-V", "Honda ZR-V",
  "Hyundai Creta", "Hyundai HB20", "Hyundai HB20S", "Hyundai ix35", "Hyundai Tucson",
  "Jeep Commander", "Jeep Compass", "Jeep Renegade", "Jeep Wrangler",
  "Jetour X70",
  "Kia Cerato", "Kia Niro", "Kia Sorento", "Kia Sportage", "Kia Stonic",
  "Leapmotor C10",
  "Mitsubishi ASX", "Mitsubishi Eclipse Cross", "Mitsubishi L200 Triton", "Mitsubishi Outlander",
  "Mitsubishi Pajero Sport",
  "Nissan Frontier", "Nissan Kicks", "Nissan March", "Nissan Sentra", "Nissan Versa",
  "Peugeot 2008", "Peugeot 208", "Peugeot 3008", "Peugeot Partner",
  "Ram 1500", "Ram 2500", "Ram Rampage",
  "Renault Captur", "Renault Duster", "Renault Kardian", "Renault Kwid", "Renault Logan",
  "Renault Master", "Renault Oroch", "Renault Sandero", "Renault Stepway",
  "Toyota Corolla", "Toyota Corolla Cross", "Toyota Etios", "Toyota Hilux", "Toyota RAV4",
  "Toyota SW4", "Toyota Yaris",
  "Volkswagen Amarok", "Volkswagen Fox", "Volkswagen Gol", "Volkswagen Jetta", "Volkswagen Nivus",
  "Volkswagen Polo", "Volkswagen Saveiro", "Volkswagen T-Cross", "Volkswagen Taos", "Volkswagen Tiguan",
  "Volkswagen Virtus", "Volkswagen Voyage",
  "Volvo XC40", "Volvo XC60",
];
