import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 36,
    paddingBottom: 48,
    paddingHorizontal: 40,
    color: "#111827",
  },
  pageHeader: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1.5,
    borderBottomColor: "#e5e7eb",
  },
  formTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 2,
  },
  leadName: {
    fontSize: 9,
    color: "#6b7280",
  },
  block: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 4,
  },
  requiredMark: {
    color: "#ef4444",
  },
  helperText: {
    fontSize: 8.5,
    color: "#6b7280",
    marginBottom: 5,
  },
  inputLine: {
    borderBottomWidth: 1,
    borderBottomColor: "#9ca3af",
    paddingBottom: 12,
    marginTop: 2,
  },
  inputBox: {
    borderWidth: 1,
    borderColor: "#9ca3af",
    borderStyle: "dashed",
    borderRadius: 3,
    padding: 8,
    minHeight: 64,
    marginTop: 2,
  },
  signatureBox: {
    borderWidth: 1,
    borderColor: "#9ca3af",
    borderRadius: 3,
    marginTop: 4,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
  },
  signatureLabel: {
    fontSize: 8,
    color: "#9ca3af",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  optionCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#6b7280",
    marginRight: 6,
  },
  optionSquare: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: "#6b7280",
    marginRight: 6,
  },
  optionText: {
    fontSize: 9.5,
    color: "#374151",
    flex: 1,
  },
  paragraphText: {
    fontSize: 9.5,
    color: "#374151",
    lineHeight: 1.5,
  },
  paragraphLine: {
    marginBottom: 3,
  },
  filledValue: {
    fontSize: 10,
    color: "#111827",
  },
  filledOptionCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#111827",
    marginRight: 6,
  },
  filledOptionSquare: {
    width: 10,
    height: 10,
    backgroundColor: "#111827",
    marginRight: 6,
  },
  starFilled: {
    fontSize: 14,
    color: "#f59e0b",
  },
  headingText: {
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 6,
  },
  rowContainer: {
    flexDirection: "column",
    gap: 10,
  },
  rowChild: {
    width: "100%",
  },
  dateBox: {
    borderWidth: 1,
    borderColor: "#9ca3af",
    borderRadius: 3,
    padding: 6,
    marginTop: 2,
    width: 160,
  },
  dateText: {
    fontSize: 9,
    color: "#9ca3af",
  },
  starsRow: {
    flexDirection: "row",
    marginTop: 4,
    gap: 4,
  },
  starText: {
    fontSize: 14,
    color: "#d1d5db",
  },
  sliderTrack: {
    height: 4,
    backgroundColor: "#e5e7eb",
    borderRadius: 2,
    marginTop: 8,
    marginBottom: 4,
    position: "relative",
  },
  sliderRange: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 2,
  },
  sliderRangeText: {
    fontSize: 8,
    color: "#9ca3af",
  },
  dropdownBox: {
    borderWidth: 1,
    borderColor: "#9ca3af",
    borderRadius: 3,
    padding: 6,
    marginTop: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownPlaceholder: {
    fontSize: 9,
    color: "#9ca3af",
  },
  dropdownArrow: {
    fontSize: 9,
    color: "#6b7280",
  },
  matrixTable: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 3,
  },
  matrixHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#f9fafb",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  matrixRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  matrixRowLast: {
    flexDirection: "row",
  },
  matrixCell: {
    flex: 1,
    padding: 5,
    fontSize: 8.5,
    color: "#374151",
    borderRightWidth: 1,
    borderRightColor: "#f3f4f6",
  },
  matrixHeaderCell: {
    flex: 1,
    padding: 5,
    fontSize: 8.5,
    fontFamily: "Helvetica-Bold",
    color: "#374151",
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
  },
  matrixLabelCell: {
    flex: 1.5,
    padding: 5,
    fontSize: 8.5,
    color: "#374151",
    borderRightWidth: 1,
    borderRightColor: "#f3f4f6",
  },
  imageContainer: {
    marginTop: 4,
    alignItems: "flex-start",
  },
  qrPlaceholder: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderStyle: "dashed",
    borderRadius: 3,
    padding: 8,
    marginTop: 4,
    alignItems: "center",
  },
  qrPlaceholderText: {
    fontSize: 8,
    color: "#9ca3af",
  },
  pageFooter: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 0.5,
    borderTopColor: "#e5e7eb",
    paddingTop: 6,
  },
  footerText: {
    fontSize: 7.5,
    color: "#9ca3af",
  },
});
