export const countries = [
  {
    country: "Brasil",
    code: "BR",
    ddi: "+55",
    flag: "https://flagcdn.com/br.svg",
  },
  {
    country: "Estados Unidos",
    code: "US",
    ddi: "+1",
    flag: "https://flagcdn.com/us.svg",
  },
  {
    country: "Canadá",
    code: "CA",
    ddi: "+1",
    flag: "https://flagcdn.com/ca.svg",
  },
  {
    country: "México",
    code: "MX",
    ddi: "+52",
    flag: "https://flagcdn.com/mx.svg",
  },
  {
    country: "Argentina",
    code: "AR",
    ddi: "+54",
    flag: "https://flagcdn.com/ar.svg",
  },
  {
    country: "Chile",
    code: "CL",
    ddi: "+56",
    flag: "https://flagcdn.com/cl.svg",
  },
  {
    country: "Colômbia",
    code: "CO",
    ddi: "+57",
    flag: "https://flagcdn.com/co.svg",
  },
  {
    country: "Peru",
    code: "PE",
    ddi: "+51",
    flag: "https://flagcdn.com/pe.svg",
  },
  {
    country: "Venezuela",
    code: "VE",
    ddi: "+58",
    flag: "https://flagcdn.com/ve.svg",
  },

  {
    country: "Portugal",
    code: "PT",
    ddi: "+351",
    flag: "https://flagcdn.com/pt.svg",
  },
  {
    country: "Espanha",
    code: "ES",
    ddi: "+34",
    flag: "https://flagcdn.com/es.svg",
  },
  {
    country: "França",
    code: "FR",
    ddi: "+33",
    flag: "https://flagcdn.com/fr.svg",
  },
  {
    country: "Alemanha",
    code: "DE",
    ddi: "+49",
    flag: "https://flagcdn.com/de.svg",
  },
  {
    country: "Itália",
    code: "IT",
    ddi: "+39",
    flag: "https://flagcdn.com/it.svg",
  },
  {
    country: "Reino Unido",
    code: "GB",
    ddi: "+44",
    flag: "https://flagcdn.com/gb.svg",
  },
  {
    country: "Holanda",
    code: "NL",
    ddi: "+31",
    flag: "https://flagcdn.com/nl.svg",
  },
  {
    country: "Suíça",
    code: "CH",
    ddi: "+41",
    flag: "https://flagcdn.com/ch.svg",
  },

  {
    country: "Japão",
    code: "JP",
    ddi: "+81",
    flag: "https://flagcdn.com/jp.svg",
  },
  {
    country: "China",
    code: "CN",
    ddi: "+86",
    flag: "https://flagcdn.com/cn.svg",
  },
  {
    country: "Índia",
    code: "IN",
    ddi: "+91",
    flag: "https://flagcdn.com/in.svg",
  },
  {
    country: "Austrália",
    code: "AU",
    ddi: "+61",
    flag: "https://flagcdn.com/au.svg",
  },
  {
    country: "África do Sul",
    code: "ZA",
    ddi: "+27",
    flag: "https://flagcdn.com/za.svg",
  },
  {
    country: "Emirados Árabes Unidos",
    code: "AE",
    ddi: "+971",
    flag: "https://flagcdn.com/ae.svg",
  },
  {
    country: "Israel",
    code: "IL",
    ddi: "+972",
    flag: "https://flagcdn.com/il.svg",
  },
  {
    country: "Rússia",
    code: "RU",
    ddi: "+7",
    flag: "https://flagcdn.com/ru.svg",
  },
];
