import type { GuideDef } from "../types";
import { GUIDE_RESULT_KINDS } from "../result-kinds";

export const PLANNER_GUIDES: GuideDef[] = [
  {
    key: "planner.external-ai",
    app: "planner",
    title: "Conectar o Claude Code (ou outra IA) ao Planner",
    summary: "Uma chave de acesso deixa a IA ler o Kit da Marca e criar rascunhos para você revisar.",
    topicPattern: /\b(claude|chatgpt|mcp|ia externa|outra ia)\b/,
    steps: [
      {
        anchor: "externalAiGenerateKey",
        route: "/integrations#external-ai",
        title: "Gere a chave",
        message: "Escolha as empresas e clique em Gerar chave. Copie o comando e rode no terminal do Claude Code.",
        position: "top",
        advanceOn: "next",
      },
      {
        anchor: "plannerCreationsTab",
        route: "/nasa-planner?tab=calendar&view=kanban&origin=ai",
        title: "Revise o que a IA criou",
        message: "No Kanban, o filtro Origem mostra só o que chegou de IA, com a origem marcada no card. Revise e aprove como qualquer post.",
        position: "bottom",
        advanceOn: "next",
      },
    ],
    finish: { title: "IA conectada! 🔌", message: "Peça no Claude Code: “use o ÓRBITA para criar os posts da semana”." },
  },
  {
    key: "planner.brand-kit",
    app: "planner",
    title: "Completar o Kit da Marca",
    summary: "Logos, cores, fontes, voz, produtos e referências para o Astro criar no tom da marca.",
    topicPattern: /\b(kit da marca|kit de marca|identidade (visual|da marca)|logos?|paleta|tipografia|brand ?kit)\b/,
    steps: [
      {
        anchor: "plannerBrandKitPage",
        route: "/nasa-planner?tab=kit",
        title: "Este é o Kit da Marca",
        message: "Um por cliente. Envie os logos em PNG transparente, as cores, as fontes e a voz da marca.",
        position: "top",
        advanceOn: "next",
      },
      {
        anchor: "plannerBrandKitMeter",
        title: "Complete os 9 itens",
        message: "O medidor mostra o que falta. Com o kit completo, o \"Gerar com o Astro\" é liberado no Novo conteúdo.",
        position: "bottom",
        advanceOn: "next",
      },
    ],
    finish: { title: "Kit no caminho certo! 🎨", message: "Quando completar, crie conteúdo em vários formatos com o Astro." },
  },
  {
    key: "planner.weekly-mind-map",
    app: "planner",
    title: "Planejar a semana em mapa mental",
    summary: "A semana vira um mapa: um tópico por dia, os posts como cards, links e notas. Dele saem os conteúdos.",
    topicPattern: /\bmapas? menta(l|is)\b/,
    steps: [
      {
        anchor: "plannerWeeklyMindMap",
        route: "/nasa-planner?tab=mindmaps",
        title: "Planejar a semana",
        message: "Escolha a semana. O mapa já vem com os dias, o tema de cada dia e os posts do roteiro. Adicione cards, links e notas, e use Criar conteúdos para virar pauta no Planner.",
        position: "bottom",
        advanceOn: "next",
      },
    ],
    finish: { title: "Mapa da semana pronto! 🗺️", message: "No celular ele abre em Lista; no computador, em Mapa." },
  },
  {
    key: "planner.weekly-script",
    app: "planner",
    title: "Montar o roteiro da semana",
    summary: "Cole o roteiro da semana, deixe o Astro separar por dia e defina o tema fixo de cada dia.",
    topicPattern: /\b(roteiro|pautas?|calendario editorial|tema do dia)\b.*\b(semana\w*|dias?)\b|\b(colar|importar)\b.*\broteiro\b/,
    steps: [
      {
        anchor: "plannerCreateMenu",
        route: "/nasa-planner?tab=calendar",
        title: "Clique em Criar",
        message: "Escolha \"Conteúdo (roteiro da semana)\" e cole o roteiro como você escreveu. O Astro separa por dia, sem reescrever.",
        position: "bottom",
        advanceOn: "next",
      },
      {
        anchor: "plannerContentFilter",
        title: "Pautas da semana",
        message: "Aqui ficam os conteúdos da semana. Em cada um, Criar abre o post já com roteiro, legenda e CTA para você fazer a arte.",
        position: "bottom",
        advanceOn: "next",
      },
      {
        anchor: "plannerWeekdayTheme",
        title: "Tema do dia",
        message: "Clique acima do dia para escrever o tema fixo (ex.: Dor + identificação). Ele vale para toda semana e vira o objetivo dos posts novos.",
        position: "bottom",
        advanceOn: "next",
        missingMessage: "Abra a visão Semana com um cliente só no filtro para ver o tema do dia.",
      },
    ],
    finish: { title: "Semana planejada! 🗓️", message: "A visão Roteiro mostra a semana em tabela: dia, formato, objetivo, conteúdo e CTA." },
  },
  {
    key: "planner.astro-generate",
    app: "planner",
    title: "Criar conteúdo com o Astro",
    summary: "Uma ideia vira roteiro, legenda e hashtags em vários formatos, no tom do Kit da Marca.",
    topicPattern: /\b(ger\w*|cri\w*|escrev\w*)\b.*\b(com (o )?astro|com ia|roteiros?|legendas?)\b/,
    steps: [
      {
        anchor: "plannerCreateMenu",
        route: "/nasa-planner?tab=calendar",
        title: "Clique em Criar",
        message: "Escolha o formato. No Roteiro você pode marcar vários formatos.",
        position: "bottom",
        advanceOn: "click",
      },
      {
        anchor: "plannerAstroGenerate",
        title: "Conte a ideia e gere",
        message: "O Astro devolve um roteiro por formato. Com o kit incompleto o botão fica desligado e mostra o que falta.",
        position: "top",
        advanceOn: "next",
        missingMessage: "Abra Criar → Novo conteúdo e role até \"Gerar com o Astro\".",
      },
    ],
    finish: { title: "Roteiros prontos! ✨", message: "Revise e crie os rascunhos; depois é só aprovar e programar." },
  },
  {
    key: "planner.comments",
    app: "planner",
    title: "Responder comentários de um post",
    summary: "Ligue a automação do Comments direto no post do Planner.",
    topicPattern: /\b(coment\w*|dm|direct|resp\w*\s+autom\w*)\b.*\b(posts?|planner|conteudos?|reels?|carross\w*)\b/,
    steps: [
      {
        anchor: "plannerCommentsPanel",
        route: "/nasa-planner?tab=calendar",
        title: "Abra Comentários automáticos",
        message: "Dentro do post, na Programação. Escolha as palavras, a DM e as respostas públicas.",
        position: "top",
        advanceOn: "next",
        missingMessage: "Abra um post do Instagram no calendário e vá em Programação.",
      },
      {
        anchor: "plannerCommentsSave",
        title: "Salve a automação",
        message: "Se o post ainda não saiu, ela liga sozinha quando ele for publicado.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerCommentsSaved,
      },
    ],
    finish: { title: "Automação pronta! 💬", message: "Quem comentar recebe a DM. Acompanhe as respostas no Comments." },
  },
  {
    key: "planner.broadcast",
    app: "planner",
    title: "Programar um disparo de WhatsApp",
    summary: "Disparo em massa pela API Oficial, direto do calendário.",
    topicPattern: /\b(dispar\w*|envio em massa|mensag\w* em massa|campanha)\b.*\b(whats\w*|zap)\b|\b(whats\w*|zap)\b.*\b(dispar\w*|em massa)\b/,
    steps: [
      {
        anchor: "plannerCreateMenu",
        route: "/nasa-planner?tab=calendar",
        title: "Clique em Criar → Disparo WhatsApp",
        message: "Aparece para clientes com número da API Oficial conectado.",
        position: "bottom",
        advanceOn: "click",
      },
      {
        anchor: "plannerBroadcastSubmit",
        title: "Escolha modelo, público e horário",
        message: "Depois clique em Programar disparo. Ele aparece no calendário e nas Campanhas.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerBroadcastScheduled,
      },
    ],
    finish: { title: "Disparo programado! 📲", message: "Sai sozinho no horário escolhido." },
  },
  {
    key: "planner.approve-post",
    app: "planner",
    title: "Aprovar um conteúdo",
    summary: "Revise e aprove o que a equipe mandou para aprovação.",
    topicPattern: /\b(aprov\w*|revis\w*|ajust\w*)\b.*\b(posts?|conteudos?|publicacoes?|stor(y|ies)|reels?)\b/,
    steps: [
      {
        anchor: "plannerApprovalTab",
        route: "/nasa-planner?tab=calendar&view=kanban",
        title: "Coluna Aguardando aprovação",
        message: "Aqui ficam os conteúdos de todos os clientes que esperam sua decisão. Clique em um para revisar.",
        position: "bottom",
        advanceOn: "click",
      },
      {
        anchor: "plannerReviewApprove",
        title: "Confira e aprove",
        message: "Abra o conteúdo, veja o checklist da marca e clique em Aprovar. Se algo precisa mudar, escreva e use Pedir ajustes.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerPostApproved,
        missingMessage: "Abra um conteúdo da coluna Aguardando aprovação primeiro.",
      },
    ],
    finish: { title: "Conteúdo aprovado! ✅", message: "Agora ele pode ser programado na aba Programação." },
  },
  {
    key: "planner.multi-account",
    app: "planner",
    title: "Publicar o mesmo conteúdo em várias contas",
    summary: "Escolha duas ou mais contas do Instagram e crie, aprove e programe uma vez só.",
    topicPattern: /\b(varias|multiplas|duas|tres|mais de uma|todas as)\s+contas\b|\bmesm[oa]\s+(posts?|conteudos?|publicac\w*|reels?|stor(y|ies))\b.*\bcontas?\b/,
    steps: [
      {
        anchor: "plannerCreateMenu",
        route: "/nasa-planner?tab=calendar",
        title: "Clique em Criar",
        message: "Escolha o formato do conteúdo que vai sair nas contas.",
        position: "bottom",
        advanceOn: "click",
      },
      {
        anchor: "plannerComposerAccounts",
        title: "Marque as contas",
        message: "Clique em cada conta do Instagram em que o conteúdo deve sair. Dá para marcar duas ou mais. Depois clique em Próximo.",
        position: "bottom",
        advanceOn: "next",
        missingMessage: "Abra o criador de conteúdo e escolha um cliente com mais de uma conta do Instagram.",
      },
      {
        anchor: "plannerPostSubmit",
        title: "Crie o conteúdo",
        message: "Preencha o roteiro e clique em Criar e continuar. O sistema cria um post para cada conta.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerPostCreated,
      },
    ],
    finish: {
      title: "Conteúdo criado nas contas! 📲",
      message: "No topo do criador você vê o status de cada conta. O que você editar vale para todas; na Programação, escolha \"Todas as contas\" para programar de uma vez.",
    },
  },
  {
    key: "planner.schedule-post",
    app: "planner",
    title: "Programar um post",
    summary: "Escolha dia e hora para o post sair sozinho.",
    topicPattern: /\b(program\w*|agend\w*|public\w*)\b.*\b(posts?|conteudos?|stor(y|ies)|reels?|carross\w*)\b/,
    steps: [
      {
        anchor: "plannerBestTimeSlot",
        route: "/nasa-planner?tab=calendar",
        title: "Use um horário sugerido",
        message: "Os cartões tracejados são horários com mais seguidores online. Clique em Programar, ou abra um post aprovado.",
        position: "bottom",
        advanceOn: "next",
        missingMessage: "Abra um post aprovado no calendário para escolher o horário.",
      },
      {
        anchor: "plannerComposerSchedule",
        title: "Escolha a data e programe",
        message: "Defina dia e hora e clique em Programar. O post sai sozinho no horário.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerPostScheduled,
      },
    ],
    finish: { title: "Post programado! 🕒", message: "Ele aparece no calendário. Se a publicação falhar, aviso você e dá para tentar de novo." },
  },
  {
    key: "planner.create-post",
    app: "planner",
    title: "Criar um post no Planner",
    summary: "Crie Feed, Carrossel, Reel ou Story para qualquer cliente.",
    topicPattern: /\b(cri\w*|plane\w*|mont\w*|fac\w*|faz\w*|novos?|roteir\w*)\b.*\b(posts?|postage(m|ns)|publicacoes?|conteudos?|stor(y|ies)|reels?|carross\w*)\b/,
    steps: [
      {
        anchor: "plannerCreateMenu",
        route: "/nasa-planner?tab=calendar",
        title: "Clique em Criar",
        message: "Escolha o formato: post no feed, carrossel, reel ou story.",
        position: "bottom",
        advanceOn: "click",
      },
      {
        anchor: "plannerComposerClient",
        title: "Escolha o cliente",
        message: "Você vê todas as empresas em que tem acesso ao Planner. Depois clique em Próximo.",
        position: "bottom",
        advanceOn: "next",
      },
      {
        anchor: "plannerPostSubmit",
        title: "Escreva o roteiro e continue",
        message: "Título, pilar e roteiro ajudam a equipe. Clique em Criar e continuar.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerPostCreated,
      },
    ],
    finish: {
      title: "Post criado! 📝",
      message: "Agora envie a arte, escreva a legenda e mande para aprovação.",
    },
  },
  {
    key: "planner.clients",
    app: "planner",
    title: "Ver o conteúdo de todos os clientes",
    summary: "Filtre o calendário por cliente.",
    topicPattern: /\b(clientes?|empresas?|marcas?)\b.*\b(planner|calendario|conteudos?|posts?)\b/,
    steps: [
      {
        anchor: "plannerClientFilter",
        route: "/nasa-planner?tab=calendar",
        title: "Escolha os clientes",
        message: "O calendário mostra todas as empresas em que você tem acesso. Marque só as que quer ver.",
        position: "bottom",
        advanceOn: "click",
      },
    ],
    finish: { title: "Pronto!", message: "Cada cliente tem uma cor de anel para você diferenciar no calendário." },
  },
  {
    key: "planner.create",
    app: "planner",
    title: "Criar um planner",
    summary: "Monte o planejamento de conteúdo de uma empresa.",
    topicPattern: /\b(cri\w*|mont\w*|fac\w*|faz\w*|novos?|novas?)\b.*\b(planners?|planejamentos?|calendario editorial)\b/,
    steps: [
      {
        anchor: "plannerNewButton",
        route: "/nasa-planner/planners",
        title: "Clique em Novo Planner",
        message: "Um planner reúne posts, campanhas e mapas mentais de uma empresa.",
        position: "bottom",
        advanceOn: "click",
      },
      {
        anchor: "plannerOrgPicker",
        title: "Escolha a empresa",
        message: "Clique aqui, escolha a empresa na lista e depois em Próximo.",
        position: "left",
        advanceOn: "next",
      },
      {
        anchor: "plannerName",
        title: "Dê um nome ao planner",
        message: "Ex.: \"Planner Q4 2026\". Depois clique em Continuar.",
        position: "left",
        advanceOn: "input",
      },
      {
        anchor: "plannerSubmit",
        title: "Clique em Criar Planner",
        message: "Só libera com nome e empresa escolhidos.",
        position: "top",
        advanceOn: "result",
        resultKind: GUIDE_RESULT_KINDS.plannerCreated,
      },
    ],
    finish: {
      title: "Planner criado! 🗓️",
      message: "Agora crie os posts. Se quiser, me peça: \"como crio um post no planner?\"",
      resultLabel: "Abrir planner",
    },
  },
];
